name: Cypress E2E Tests

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests (Chrome)
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          build: npm run build || echo "No build step"
          start: npm start || echo "No start step"
          wait-on: http-get://localhost:3000 || echo "No server needed"
          command: npx cypress run --env TAGS="@regressao"

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
